## Images 2 database

In [1]:
# test
%cd '/Volumes/Projects/3drn'

/Volumes/Projects/3drn


## Feature extractor

In [2]:
import os
DATASET_PATH = 'data/xe_F1_khan_60_test2'
assert os.path.exists(DATASET_PATH), f"Dataset path {DATASET_PATH} does not exist."

!colmap feature_extractor \
    --database_path $DATASET_PATH/database.db \
    --image_path $DATASET_PATH/images \
    --SiftExtraction.max_num_features 6144 \
    --SiftExtraction.max_image_size 2000 \
    --SiftExtraction.estimate_affine_shape 1 

I20250512 22:32:03.387099 769081 misc.cc:44] 
Feature extraction
I20250512 22:32:03.387295 769097 sift.cc:717] Creating Covariant SIFT CPU feature extractor
I20250512 22:32:03.387297 769096 sift.cc:717] Creating Covariant SIFT CPU feature extractor
I20250512 22:32:03.387307 769098 sift.cc:717] Creating Covariant SIFT CPU feature extractor
I20250512 22:32:03.387315 769099 sift.cc:717] Creating Covariant SIFT CPU feature extractor
I20250512 22:32:03.387317 769100 sift.cc:717] Creating Covariant SIFT CPU feature extractor
I20250512 22:32:03.387323 769101 sift.cc:717] Creating Covariant SIFT CPU feature extractor
I20250512 22:32:03.387331 769102 sift.cc:717] Creating Covariant SIFT CPU feature extractor
I20250512 22:32:03.387333 769103 sift.cc:717] Creating Covariant SIFT CPU feature extractor
I20250512 22:32:03.387338 769104 sift.cc:717] Creating Covariant SIFT CPU feature extractor
I20250512 22:32:03.387342 769105 sift.cc:717] Creating Covariant SIFT CPU feature extractor
I20250512 22:32

In [25]:
DATASET_PATH

'data/xe_F1_khan_60'

## Exhausive matcher

In [8]:
assert os.path.exists(f"{DATASET_PATH}/database.db"), "Database file was not created."
assert os.path.exists(f"{DATASET_PATH}/images"), "Images directory was not created."
temp_path = f"{DATASET_PATH}/database.db"
!colmap exhaustive_matcher \
    --database_path $temp_path \
    --SiftMatching.max_ratio 0.85


I20250416 23:02:00.509509 8308591 misc.cc:44] 
Feature matching
I20250416 23:02:00.522176 8308592 sift.cc:1426] Creating SIFT GPU feature matcher
I20250416 23:02:00.544878 8308591 pairing.cc:168] Generating exhaustive image pairs...
I20250416 23:02:00.544893 8308591 pairing.cc:201] Matching block [1/2, 1/2]
I20250416 23:02:04.256991 8308591 feature_matching.cc:46] in 3.712s
I20250416 23:02:04.258081 8308591 pairing.cc:201] Matching block [1/2, 2/2]
I20250416 23:02:04.406284 8308591 feature_matching.cc:46] in 0.148s
I20250416 23:02:04.406589 8308591 pairing.cc:201] Matching block [2/2, 1/2]
I20250416 23:02:05.772403 8308591 feature_matching.cc:46] in 1.366s
I20250416 23:02:05.775379 8308591 pairing.cc:201] Matching block [2/2, 2/2]
I20250416 23:02:05.906663 8308591 feature_matching.cc:46] in 0.131s
I20250416 23:02:05.906852 8308591 timer.cc:91] Elapsed time: 0.090 [minutes]


## Sparse reconstruction

In [3]:
import os

TEMP_database_path = f"{DATASET_PATH}/database.db"
TEMP_image_path = f"{DATASET_PATH}/images_test"
TEMP_out_path = f"{DATASET_PATH}/sparse"
os.makedirs(TEMP_out_path, exist_ok=True)
assert os.path.exists(TEMP_database_path), f"Database path {TEMP_database_path} does not exist."
assert os.path.exists(TEMP_image_path), f"Image path {TEMP_image_path} does not exist."
assert os.path.exists(TEMP_out_path), f"Output path {TEMP_out_path} does not exist."
!colmap mapper \
    --database_path $TEMP_database_path \
    --image_path $TEMP_image_path \
    --out $TEMP_out_path \
    --Mapper.min_num_matches 15 \
    --Mapper.ba_global_max_num_iterations 50

I20250512 22:32:13.126223 769273 incremental_pipeline.cc:251] Loading database
I20250512 22:32:13.128191 769273 database_cache.cc:66] Loading cameras...
I20250512 22:32:13.128225 769273 database_cache.cc:76]  60 in 0.000s
I20250512 22:32:13.128232 769273 database_cache.cc:84] Loading matches...
I20250512 22:32:13.140194 769273 database_cache.cc:89]  1766 in 0.012s
I20250512 22:32:13.140205 769273 database_cache.cc:105] Loading images...
I20250512 22:32:13.157604 769273 database_cache.cc:153]  60 in 0.017s (connected 60)
I20250512 22:32:13.157614 769273 database_cache.cc:164] Loading pose priors...
I20250512 22:32:13.157727 769273 database_cache.cc:175]  0 in 0.000s
I20250512 22:32:13.157732 769273 database_cache.cc:184] Building correspondence graph...
I20250512 22:32:13.173105 769273 database_cache.cc:210]  in 0.015s (ignored 0)
I20250512 22:32:13.173276 769273 timer.cc:91] Elapsed time: 0.001 [minutes]
I20250512 22:32:13.174991 769273 incremental_pipeline.cc:297] Finding good initial

In [9]:
# Convert .bin to .txt
TEMP_out_path = f"{DATASET_PATH}/sparse/0"
!colmap model_converter \
    --input_path $TEMP_out_path \
    --output_path $TEMP_out_path \
    --output_type TXT


## DENSE

In [28]:
# TEMP_image_path = f"{DATASET_PATH}/images"
# TEMP_input_path = f"{DATASET_PATH}/sparse/0"
# TEMP_output_path = f"{DATASET_PATH}/dense"
# os.makedirs(TEMP_output_path, exist_ok=True)
# assert os.path.exists(TEMP_image_path), f"Image path {TEMP_image_path} does not exist."
# assert os.path.exists(TEMP_input_path), f"Input path {TEMP_input_path} does not exist."
# assert os.path.exists(TEMP_output_path), f"Output path {TEMP_output_path} does not exist."

# !colmap image_undistorter \
#     --image_path $TEMP_image_path \
#     --input_path $TEMP_input_path \
#     --output_path $TEMP_output_path \
#     --output_type COLMAP \
#     --max_image_size 2000 \


## Patch match stereo -> dense -> .ply

In [ ]:
# ## Cần GPU

# TEMP_workspace_path = f"{DATASET_PATH}/dense"
# assert os.path.exists(TEMP_workspace_path), f"Workspace path {TEMP_workspace_path} does not exist."

# !colmap patch_match_stereo \
#     --workspace_path $TEMP_workspace_path \
#     --workspace_format COLMAP \
#     --PatchMatchStereo.geom_consistency true \
#     --PatchMatchStereo.use_gpu 1 \

# TEMP_workspace_path = f"{DATASET_PATH}/dense"
# assert os.path.exists(TEMP_workspace_path), f"Workspace path {TEMP_workspace_path} does not exist."
# TEMP_output_path = f"{DATASET_PATH}/fused.ply"

# !colmap stereo_fusion \
#     --workspace_path $DATASET_PATH/dense \
#     --workspace_format COLMAP \
#     --input_type geometric \
#     --output_path $DATASET_PATH/dense/fused.ply

E20250410 09:18:47.969971 6560374 mvs.cc:80] Dense stereo reconstruction requires CUDA, which is not available on your system.


## Stereo fusion -> .ply

In [29]:
TEMP_input_path = f"{DATASET_PATH}/sparse/0"
TEMP_output_path = f"{DATASET_PATH}/output.ply"
assert os.path.exists(TEMP_input_path), f"Input path {TEMP_input_path} does not exist."

!colmap model_converter \
    --input_path $TEMP_input_path \
    --output_path $TEMP_output_path \
    --output_type PLY


In [4]:
## split train test from cameras.bin and images.bin and points3d.bin and database.db
import os
from colmap.scripts.python.read_write_model import read_cameras_binary, read_images_binary, read_points3D_binary
from colmap.scripts.python.read_write_model import write_cameras_binary, write_images_binary, write_points3D_binary


def split_test(dataset_path, llffhold=8):
    """
    Split the dataset into train and test sets.
    
    Parameters:
        dataset_path (str): Path to the dataset directory.
        train_ratio (float): Ratio of training data (default is 0.8).
    """
    # Load the database
    database_path = os.path.join(dataset_path, 'database.db')
    assert os.path.exists(database_path), f"Database path {database_path} does not exist."
    
    # Load the cameras, images, and points3D
    cameras_path = os.path.join(dataset_path, 'sparse/0/cameras.bin')
    images_path = os.path.join(dataset_path, 'sparse/0/images.bin')
    points3d_path = os.path.join(dataset_path, 'sparse/0/points3D.bin')
    
    assert os.path.exists(cameras_path), f"Cameras path {cameras_path} does not exist."
    assert os.path.exists(images_path), f"Images path {images_path} does not exist."
    assert os.path.exists(points3d_path), f"Points3D path {points3d_path} does not exist."
    
    # Load the cameras
    cameras = read_cameras_binary(cameras_path)
    assert cameras is not None, "Failed to load cameras."
    # Load the images
    images = read_images_binary(images_path)
    assert images is not None, "Failed to load images."
    # Load the points3D
    points3D = read_points3D_binary(points3d_path)
    assert points3D is not None, "Failed to load points3D."
    # Split the images into train and test sets; if image_id % llffhold == 0, it's in the test set
    test_img_dir = os.path.join(dataset_path, 'images_test')
    test_img_name_list = os.listdir(test_img_dir)
    image_ids = list(images.keys())

    a_list = [images[image_id].name for image_id in image_ids]
    print("Image names in the dataset:", a_list)
    print("Test image names:", test_img_name_list)
    test_image_ids = [image_id for image_id in image_ids if images[image_id].name in test_img_name_list]

    # image_ids = list(images.keys())
    # image_ids.sort()
    # test_image_ids = []
    # for i, image_id in enumerate(image_ids):
    #     print("image :", images[image_id])
    #     if i % llffhold == 0:
    #         test_image_ids.append(image_id)
    print("Test image IDs:", test_image_ids)
    
    # Create directories for train and test sets
    test_dir = os.path.join(dataset_path, 'test')
    os.makedirs(test_dir, exist_ok=True)
    # Save the train and test sets
    test_cameras_path = os.path.join(test_dir, 'cameras.bin')
    test_images_path = os.path.join(test_dir, 'images.bin')
    test_points3D_path = os.path.join(test_dir, 'points3D.bin')
    # Save the cameras
    write_cameras_binary(cameras, test_cameras_path)
    # Save the images
    test_images = {image_id: images[image_id] for image_id in test_image_ids}
    write_images_binary(test_images, test_images_path)
    # Save the points3D
    test_points3D = {point3D_id: points3D[point3D_id] for point3D_id in points3D.keys() if point3D_id in test_image_ids}
    write_points3D_binary(test_points3D, test_points3D_path)

split_test(DATASET_PATH, llffhold=8)


Image names in the dataset: ['frame_0000.png', 'frame_0040.png', 'frame_0048.png', 'frame_0016.png', 'frame_0032.png', 'frame_0008.png', 'frame_0024.png', 'frame_0056.png', 'frame_0003.png', 'frame_0002.png', 'frame_0004.png', 'frame_0005.png', 'frame_0001.png', 'frame_0010.png', 'frame_0007.png', 'frame_0014.png', 'frame_0011.png', 'frame_0012.png', 'frame_0013.png', 'frame_0009.png', 'frame_0006.png', 'frame_0015.png', 'frame_0017.png', 'frame_0018.png', 'frame_0019.png', 'frame_0020.png', 'frame_0029.png', 'frame_0028.png', 'frame_0021.png', 'frame_0022.png', 'frame_0026.png', 'frame_0025.png', 'frame_0030.png', 'frame_0023.png', 'frame_0027.png', 'frame_0031.png', 'frame_0033.png', 'frame_0035.png', 'frame_0034.png', 'frame_0036.png', 'frame_0038.png', 'frame_0039.png', 'frame_0042.png', 'frame_0044.png', 'frame_0037.png', 'frame_0046.png', 'frame_0041.png', 'frame_0043.png', 'frame_0045.png', 'frame_0047.png', 'frame_0049.png', 'frame_0050.png', 'frame_0051.png', 'frame_0052.png',

## Cal metrics from mesh.obj

In [77]:
import os
import cv2
import torch
import lpips
import numpy as np
import open3d as o3d
import pyrender
import trimesh
from tqdm import tqdm
from skimage.metrics import structural_similarity as compare_ssim
from skimage.metrics import peak_signal_noise_ratio as compare_psnr
from colmap.scripts.python.read_write_model import read_cameras_binary, read_images_binary

# =======================
# Load Camera Intrinsics
# =======================
# def load_intrinsics(camera):
#     print('camera info: ', camera)
#     fx, fy, cx, cy = camera.params[:4]
#     width, height = int(camera.width), int(camera.height)
#     K = np.array([[fx, 0, cx],
#                   [0, fy, cy],
#                   [0,  0,  1]])
#     return K, width, height
def load_intrinsics(camera):
    model = camera.model

    if model in ['SIMPLE_PINHOLE', 'SIMPLE_RADIAL']:
        f, cx, cy = camera.params[:3]
        fx = fy = f
        if cy < 1e-2:
            print("⚠️ Detected invalid cy (≈ 0), overriding to image center.")
            cy = camera.height / 2
    elif model == 'PINHOLE':
        fx, fy, cx, cy = camera.params[:4]
    else:
        raise ValueError(f"⚠️ Unsupported camera model: {model}")

    K = np.array([[fx, 0, cx],
                  [0, fy, cy],
                  [0,  0,  1]])
    width, height = int(camera.width), int(camera.height)

    print(f"fx: {fx}  - fy: {fy}  - cx: {cx}  - cy: {cy}")
    if abs(cx - width / 2) > width * 0.1 or abs(cy - height / 2) > height * 0.1:
        print("⚠️  Warning: cx, cy lệch xa trung tâm ảnh. Kiểm tra lại nội tại COLMAP hoặc ảnh đã resize.")

    print("🎯 Intrinsic matrix K:\n", K)
    return K, width, height
# =======================
# Load Camera Extrinsics
# =======================
def load_extrinsics(image):
    R = image.qvec2rotmat()
    t = image.tvec.reshape(3, 1)
    # Colmap: world to camera => cần nghịch đảo để camera to world
    Rt = np.eye(4)
    Rt[:3, :3] = R
    Rt[:3, 3] = t[:, 0]
    return np.linalg.inv(Rt)

# =======================
# Render Image
# =======================
def render_scene(mesh, K, width, height, pose):
    scene = pyrender.Scene(bg_color=[0, 0, 0, 0], ambient_light=[0.3, 0.3, 0.3])
    scene.add(mesh)

    camera = pyrender.IntrinsicsCamera(
        fx=K[0, 0], fy=K[1, 1],
        cx=K[0, 2], cy=K[1, 2],
        znear=0.1, zfar=100.0
    )

    # Convert Colmap to OpenGL camera frame
    flip_transform = np.eye(4)
    flip_transform[1, 1] = -1
    flip_transform[2, 2] = -1
    pose = pose @ flip_transform

    scene.add(camera, pose=pose)

    # light = pyrender.DirectionalLight(color=np.ones(3), intensity=2.0)
    # scene.add(light, pose=pose)

    renderer = pyrender.OffscreenRenderer(viewport_width=width, viewport_height=height)
    color, depth = renderer.render(scene, flags=pyrender.RenderFlags.FLAT | pyrender.RenderFlags.SKIP_CULL_FACES)

    renderer.delete()
    return color

# =======================
# Compute Metrics
# =======================
def compute_metrics(gt_image, pred_image, loss_fn_alex):
    # Resize pred_image if needed
    if gt_image.shape != pred_image.shape:
        pred_image = cv2.resize(pred_image, (gt_image.shape[1], gt_image.shape[0]))

    # Convert to float32
    gt_float = gt_image.astype(np.float32) / 255.0
    pred_float = pred_image.astype(np.float32) / 255.0

    # PSNR
    psnr = compare_psnr(gt_float, pred_float, data_range=1.0)

    # SSIM
    print(f"GT image shape: {gt_image.shape}")
    print(f"Predicted image shape: {pred_image.shape}")
    # ssim = compare_ssim(gt_float, pred_float, multichannel=True, data_range=1.0)
    ssim = compare_ssim(gt_float, pred_float, multichannel=True, data_range=1.0, win_size=3)
    
    # LPIPS
    gt_tensor = torch.tensor(gt_float).permute(2, 0, 1).unsqueeze(0).float()
    pred_tensor = torch.tensor(pred_float).permute(2, 0, 1).unsqueeze(0).float()
    lpips_value = loss_fn_alex(gt_tensor, pred_tensor).item()
    # print(lpips_value)
    if lpips_value=='nan':
        lpips_value = 1
    return psnr, ssim, lpips_value

# =======================
# Main
# =======================
def main():
    # sparse_dir = "/Volumes/Projects/3drn/data/new_project_xeF1_100/sparse/0"
    sparse_dir = "/Volumes/Projects/3drn/data/xe_F1_khan_60_test2/test"
    ply_file = "/Volumes/Projects/3drn/data/new_project_xeF1_100/dense/0/xe_F1_100_chualoc.obj"
    images_dir = "/Volumes/Projects/3drn/data/xe_F1_khan_60_test2/images_test"
    output_dir= "/Volumes/Projects/3drn/data/xe_F1_khan_60_test2/rendered_images_70_May12"

    # data_dir = "data"
    # images_dir = os.path.join(data_dir, "images")
    # sparse_dir = os.path.join(data_dir, "sparse/0")
    # ply_file = os.path.join(data_dir, "dense/fused.ply")
    # output_dir = os.path.join(data_dir, "rendered")
    os.makedirs(output_dir, exist_ok=True)

    print("✅ Loading cameras and images...")
    cameras = read_cameras_binary(os.path.join(sparse_dir, "cameras.bin"))
    images = read_images_binary(os.path.join(sparse_dir, "images.bin"))


    print("✅ Loading mesh...")
    # Load the .ply file
    mesh = trimesh.load(ply_file)


    # Check if the loaded object is a Scene
    if isinstance(mesh, trimesh.Scene):
        # Extract the first geometry from the Scene
        mesh = mesh.dump(concatenate=True)


    print('point3D.bin : ', os.path.join(sparse_dir, "points3D.bin"))
    # mesh = align_mesh_to_sparse(mesh, os.path.join(sparse_dir, "points3D.bin"))
    # mesh = align_mesh_with_colmap(mesh, os.path.join(sparse_dir, "points3D.bin"))

    mesh = pyrender.Mesh.from_trimesh(mesh)
    

    # # Assume single camera
    # camera = list(cameras.values())[0]
    # # camera = list(cameras.values())[3]
    # K, width, height = load_intrinsics(camera)

    loss_fn_alex = lpips.LPIPS(net='alex')

    psnr_list, ssim_list, lpips_list = [], [], []

    for image_name, image in tqdm(images.items(), desc="Rendering and comparing"):
        pose = load_extrinsics(image)

        camera = cameras[image.camera_id]
        K, width, height = load_intrinsics(camera)

        # Render
        color = render_scene(mesh, K, width, height, pose)
        output_path = os.path.join(output_dir, os.path.splitext(image.name)[0] + ".png")
        cv2.imwrite(output_path, cv2.cvtColor(color, cv2.COLOR_RGB2BGR))

        # Load ground truth
        gt_path = os.path.join(images_dir, image.name)
        if not os.path.exists(gt_path):
            print(f"⚠️ Ground truth image {gt_path} not found, skipping.")
            continue
        gt_image = cv2.imread(gt_path)
        pred_image = color

        # Compute metrics
        psnr, ssim, lpips_value = compute_metrics(gt_image, pred_image, loss_fn_alex)
        psnr_list.append(psnr)
        ssim_list.append(ssim)
        lpips_list.append(lpips_value)

        print(f"{image.name}: PSNR={psnr:.2f}, SSIM={ssim:.3f}, LPIPS={lpips_value:.3f}")

    print("\n✅ Done! Average metrics:")
    print(f"PSNR: {np.mean(psnr_list):.2f}")
    print(f"SSIM: {np.mean(ssim_list):.3f}")
    print(f"LPIPS: {np.mean(lpips_list):.3f}")

if __name__ == "__main__":
    main()


✅ Loading cameras and images...
✅ Loading mesh...


/Volumes/Projects/opt/anaconda3/lib/python3.12/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/Volumes/Projects/opt/anaconda3/lib/python3.12/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


point3D.bin :  /Volumes/Projects/3drn/data/xe_F1_khan_60_test2/test/points3D.bin
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
Loading model from: /Volumes/Projects/opt/anaconda3/lib/python3.12/site-packages/lpips/weights/v0.1/alex.pth


Rendering and comparing:   0%|          | 0/8 [00:00<?, ?it/s]

fx: 1146.4364194057184  - fy: 1146.4364194057184  - cx: 640.0  - cy: 360.0
🎯 Intrinsic matrix K:
 [[1.14643642e+03 0.00000000e+00 6.40000000e+02]
 [0.00000000e+00 1.14643642e+03 3.60000000e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
GT image shape: (720, 1280, 3)
Predicted image shape: (720, 1280, 3)


Rendering and comparing:  12%|█▎        | 1/8 [00:00<00:03,  2.08it/s]

frame_0000.png: PSNR=18.62, SSIM=0.368, LPIPS=0.292
fx: 1134.515868992312  - fy: 1134.515868992312  - cx: 640.0  - cy: 360.0
🎯 Intrinsic matrix K:
 [[1.13451587e+03 0.00000000e+00 6.40000000e+02]
 [0.00000000e+00 1.13451587e+03 3.60000000e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
GT image shape: (720, 1280, 3)
Predicted image shape: (720, 1280, 3)


Rendering and comparing:  25%|██▌       | 2/8 [00:00<00:02,  2.15it/s]

frame_0040.png: PSNR=21.94, SSIM=0.587, LPIPS=0.194
fx: 1151.5021007990495  - fy: 1151.5021007990495  - cx: 640.0  - cy: 360.0
🎯 Intrinsic matrix K:
 [[1.1515021e+03 0.0000000e+00 6.4000000e+02]
 [0.0000000e+00 1.1515021e+03 3.6000000e+02]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00]]
GT image shape: (720, 1280, 3)
Predicted image shape: (720, 1280, 3)


Rendering and comparing:  38%|███▊      | 3/8 [00:01<00:02,  2.18it/s]

frame_0048.png: PSNR=22.21, SSIM=0.687, LPIPS=0.203
fx: 1142.4677776724109  - fy: 1142.4677776724109  - cx: 640.0  - cy: 360.0
🎯 Intrinsic matrix K:
 [[1.14246778e+03 0.00000000e+00 6.40000000e+02]
 [0.00000000e+00 1.14246778e+03 3.60000000e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
GT image shape: (720, 1280, 3)
Predicted image shape: (720, 1280, 3)


Rendering and comparing:  50%|█████     | 4/8 [00:01<00:01,  2.19it/s]

frame_0016.png: PSNR=20.17, SSIM=0.623, LPIPS=0.248
fx: 1131.1081880188333  - fy: 1131.1081880188333  - cx: 640.0  - cy: 360.0
🎯 Intrinsic matrix K:
 [[1.13110819e+03 0.00000000e+00 6.40000000e+02]
 [0.00000000e+00 1.13110819e+03 3.60000000e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
GT image shape: (720, 1280, 3)
Predicted image shape: (720, 1280, 3)


Rendering and comparing:  62%|██████▎   | 5/8 [00:02<00:01,  2.19it/s]

frame_0032.png: PSNR=20.52, SSIM=0.532, LPIPS=0.225
fx: 1158.615018164056  - fy: 1158.615018164056  - cx: 640.0  - cy: 360.0
🎯 Intrinsic matrix K:
 [[1.15861502e+03 0.00000000e+00 6.40000000e+02]
 [0.00000000e+00 1.15861502e+03 3.60000000e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
GT image shape: (720, 1280, 3)
Predicted image shape: (720, 1280, 3)


Rendering and comparing:  75%|███████▌  | 6/8 [00:02<00:00,  2.20it/s]

frame_0008.png: PSNR=19.42, SSIM=0.545, LPIPS=0.265
fx: 1157.1897566325913  - fy: 1157.1897566325913  - cx: 640.0  - cy: 360.0
🎯 Intrinsic matrix K:
 [[1.15718976e+03 0.00000000e+00 6.40000000e+02]
 [0.00000000e+00 1.15718976e+03 3.60000000e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
GT image shape: (720, 1280, 3)
Predicted image shape: (720, 1280, 3)


Rendering and comparing:  88%|████████▊ | 7/8 [00:03<00:00,  2.19it/s]

frame_0024.png: PSNR=20.24, SSIM=0.566, LPIPS=0.256
fx: 1149.9598159342056  - fy: 1149.9598159342056  - cx: 640.0  - cy: 360.0
🎯 Intrinsic matrix K:
 [[1.14995982e+03 0.00000000e+00 6.40000000e+02]
 [0.00000000e+00 1.14995982e+03 3.60000000e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
GT image shape: (720, 1280, 3)
Predicted image shape: (720, 1280, 3)


Rendering and comparing: 100%|██████████| 8/8 [00:03<00:00,  2.19it/s]

frame_0056.png: PSNR=20.19, SSIM=0.535, LPIPS=0.219

✅ Done! Average metrics:
PSNR: 20.41
SSIM: 0.555
LPIPS: 0.238


In [ ]:
!colmap poisson_mesher \
    --input_path /Volumes/Projects/3drn/data/new_project_xeF1_100/dense/0/fused.ply \
    --output_path /Volumes/Projects/3drn/data/new_project_xeF1_100/dense/0/mesh.ply \


[WARNING] Bad average root: nan
	(-0.215303 -0.220932) (0.457721)
[WARNING] Bad average root: nan
	(-0.274327 -0.215303) (0.457721)
[ERROR] Failed to close loop [8: 194 154 78] | (492401): 11118271948396616


In [ ]:
import open3d as o3d

# path_mesh = '/Volumes/Projects/3drn/data/new_project_xeF1_100/dense/0/fused.ply'
# mesh = o3d.io.read_point_cloud(path_mesh)
# Đọc mesh từ file (ví dụ file .obj)
path_mesh = '/Volumes/Projects/3drn/data/new_project_xeF1_100/dense/0/xe_F1_100_chualoc.obj'
mesh = o3d.io.read_triangle_mesh(path_mesh)

# Kiểm tra xem mesh có hợp lệ không
if not mesh.is_empty():
    print("Mesh is loaded successfully.")
else:
    print("Failed to load mesh.")

# Hiển thị mesh
o3d.visualization.draw_geometries([mesh])


In [33]:
import os
import numpy as np
import open3d as o3d
from colmap.scripts.python.read_write_model import read_images_binary, read_cameras_binary

def load_camera_frustum(K, width, height, scale=0.2):
    fx, fy, cx, cy = K[0,0], K[1,1], K[0,2], K[1,2]

    # Camera frustum points in camera space
    points = [
        [0, 0, 0],  # camera center
        [(0 - cx) / fx, (0 - cy) / fy, 1.0],
        [(width - cx) / fx, (0 - cy) / fy, 1.0],
        [(width - cx) / fx, (height - cy) / fy, 1.0],
        [(0 - cx) / fx, (height - cy) / fy, 1.0],
    ]
    points = np.array(points) * scale

    lines = [
        [0, 1], [0, 2], [0, 3], [0, 4],
        [1, 2], [2, 3], [3, 4], [4, 1],
    ]

    colors = [[1, 0, 0] for _ in lines]  # red frustum
    line_set = o3d.geometry.LineSet(
        points=o3d.utility.Vector3dVector(points),
        lines=o3d.utility.Vector2iVector(lines),
    )
    line_set.colors = o3d.utility.Vector3dVector(colors)
    return line_set

def create_camera_geometry(pose, K, width, height, scale=0.2):
    frustum = load_camera_frustum(K, width, height, scale)
    frustum.transform(pose)
    return frustum

def main():
    # === PATHS ===
    sparse_dir = "/Volumes/Projects/3drn/data/xe_F1_khan_60_test2/test"
    mesh_path = "/Volumes/Projects/3drn/data/new_project_xeF1_100/dense/0/xe_F1_100_chualoc.obj"

    # === LOAD COLMAP ===
    cameras = read_cameras_binary(os.path.join(sparse_dir, "cameras.bin"))
    images = read_images_binary(os.path.join(sparse_dir, "images.bin"))
    camera = list(cameras.values())[0]
    fx, fy, cx, cy = camera.params[:4]
    width, height = int(camera.width), int(camera.height)
    K = np.array([[fx, 0, cx],
                  [0, fy, cy],
                  [0,  0,  1]])

    # === LOAD MESH ===
    mesh = o3d.io.read_triangle_mesh(mesh_path)
    mesh.compute_vertex_normals()

    # === CREATE CAMERA GEOMETRY ===
    geometries = [mesh]
    for image in images.values():
        R = image.qvec2rotmat()
        t = image.tvec.reshape(3, 1)
        Rt = np.eye(4)
        Rt[:3, :3] = R
        Rt[:3, 3] = t[:, 0]

        cam_to_world = np.linalg.inv(Rt)

        # Flip to Open3D (z forward, y up)
        flip_transform = np.eye(4)
        flip_transform[1, 1] = -1
        flip_transform[2, 2] = -1
        cam_to_world = cam_to_world @ flip_transform

        frustum = create_camera_geometry(cam_to_world, K, width, height, scale=0.3)
        geometries.append(frustum)

    # === VISUALIZE ===
    o3d.visualization.draw_geometries(geometries)

if __name__ == "__main__":
    main()


In [46]:
import os
import numpy as np
import open3d as o3d
from colmap.scripts.python.read_write_model import read_cameras_binary, read_images_binary, read_points3D_binary

def load_camera_frustum(K, width, height, scale=0.2):
    fx, fy, cx, cy = K[0, 0], K[1, 1], K[0, 2], K[1, 2]
    points = [
        [0, 0, 0],
        [(0 - cx) / fx, (0 - cy) / fy, 1.0],
        [(width - cx) / fx, (0 - cy) / fy, 1.0],
        [(width - cx) / fx, (height - cy) / fy, 1.0],
        [(0 - cx) / fx, (height - cy) / fy, 1.0],
    ]
    points = np.array(points) * scale
    lines = [
        [0, 1], [0, 2], [0, 3], [0, 4],
        [1, 2], [2, 3], [3, 4], [4, 1],
    ]
    colors = [[1, 0, 0] for _ in lines]  # red lines
    frustum = o3d.geometry.LineSet(
        points=o3d.utility.Vector3dVector(points),
        lines=o3d.utility.Vector2iVector(lines)
    )
    frustum.colors = o3d.utility.Vector3dVector(colors)
    return frustum

def create_camera_geometry(pose, K, width, height, scale=0.2):
    frustum = load_camera_frustum(K, width, height, scale)
    frustum.transform(pose)
    return frustum

def load_colmap_points(points3d_path):
    points3D = read_points3D_binary(points3d_path)
    xyz = [p.xyz for p in points3D.values()]
    pc = o3d.geometry.PointCloud()
    pc.points = o3d.utility.Vector3dVector(np.array(xyz))
    pc.paint_uniform_color([0, 1, 0])  # green
    return pc

def main():
    # === PATHS ===
    sparse_dir = "/Volumes/Projects/3drn/data/xe_F1_khan_60_test2/test"
    mesh_path = "/Volumes/Projects/3drn/data/new_project_xeF1_100/dense/0/xe_F1_100_chualoc.obj"
    points3d_path = os.path.join(sparse_dir, "points3D.bin")

    # === LOAD COLMAP ===
    cameras = read_cameras_binary(os.path.join(sparse_dir, "cameras.bin"))
    images = read_images_binary(os.path.join(sparse_dir, "images.bin"))
    camera = list(cameras.values())[0]
    fx, fy, cx, cy = camera.params[:4]
    width, height = int(camera.width), int(camera.height)
    K = np.array([[fx, 0, cx],
                  [0, fy, cy],
                  [0,  0,  1]])

    # === LOAD MESH ===
    mesh = o3d.io.read_triangle_mesh(mesh_path)
    mesh.compute_vertex_normals()

    # === LOAD POINT CLOUD FROM COLMAP ===
    points3D = load_colmap_points(points3d_path)

    # === COLLECT GEOMETRIES ===
    geometries = [mesh, points3D]

    for image in images.values():
        R = image.qvec2rotmat()
        t = image.tvec.reshape(3, 1)
        Rt = np.eye(4)
        Rt[:3, :3] = R
        Rt[:3, 3] = t[:, 0]
        cam_to_world = np.linalg.inv(Rt)

        # Flip to Open3D (z forward, y up)
        flip = np.eye(4)
        flip[1, 1] = -1
        flip[2, 2] = -1
        cam_to_world = cam_to_world @ flip

        frustum = create_camera_geometry(cam_to_world, K, width, height, scale=0.3)
        geometries.append(frustum)

    # === VISUALIZE ALL ===
    o3d.visualization.draw_geometries(geometries)

if __name__ == "__main__":
    main()


In [38]:
import open3d as o3d
import numpy as np
from colmap.scripts.python.read_write_model import read_points3D_binary
import os

def load_colmap_points(points3d_path):
    points3D = read_points3D_binary(points3d_path)
    xyz = [p.xyz for p in points3D.values()]
    pc = o3d.geometry.PointCloud()
    pc.points = o3d.utility.Vector3dVector(np.array(xyz))
    pc.paint_uniform_color([0, 1, 0])  # green
    return pc

def align_mesh_with_colmap(mesh_path, points3d_path):
    # Load mesh and convert to point cloud
    mesh = o3d.io.read_triangle_mesh(mesh_path)
    mesh.compute_vertex_normals()
    mesh_pc = mesh.sample_points_uniformly(number_of_points=10000)

    # Load COLMAP point cloud
    colmap_pc = load_colmap_points(points3d_path)

    # ICP Alignment
    threshold = 1.0  # distance threshold for ICP
    icp_result = o3d.pipelines.registration.registration_icp(
        mesh_pc, colmap_pc, threshold,
        np.eye(4),
        o3d.pipelines.registration.TransformationEstimationPointToPoint()
    )

    print("ICP fitness:", icp_result.fitness)
    print("ICP inlier RMSE:", icp_result.inlier_rmse)
    print("ICP transformation:\n", icp_result.transformation)

    # Apply transform to original mesh
    mesh.transform(icp_result.transformation)

    # Visualize result
    mesh_pc_aligned = mesh.sample_points_uniformly(number_of_points=10000)
    mesh_pc_aligned.paint_uniform_color([1, 0, 0])  # red
    o3d.visualization.draw_geometries([mesh_pc_aligned, colmap_pc])

    # Save aligned mesh if needed
    # o3d.io.write_triangle_mesh("aligned_mesh.ply", mesh)

    return mesh  # aligned mesh

if __name__ == "__main__":
    mesh_path = "/Volumes/Projects/3drn/data/new_project_xeF1_100/dense/0/xe_F1_100_chualoc.obj"
    points3d_path = "/Volumes/Projects/3drn/data/xe_F1_khan_60_test2/test/points3D.bin"

    aligned_mesh = align_mesh_with_colmap(mesh_path, points3d_path)


ICP fitness: 0.8108
ICP inlier RMSE: 0.5366117087743922
ICP transformation:
 [[ 0.98235532 -0.13663757  0.12770356 -0.42618274]
 [ 0.15387013  0.97860735 -0.13657102  0.49515893]
 [-0.10631091  0.15381103  0.98236457 -0.60959315]
 [ 0.          0.          0.          1.        ]]


In [70]:
import os
import cv2
import numpy as np
import pyrender
import trimesh
from colmap.scripts.python.read_write_model import read_images_binary, read_cameras_binary

def load_intrinsics(camera):
    fx, fy, cx, cy = camera.params[:4]
    K = np.array([[fx, 0, cx],
                  [0, fy, cy],
                  [0,  0,  1]])
    return K, int(camera.width), int(camera.height)

def load_extrinsics(image):
    R = image.qvec2rotmat()
    t = image.tvec.reshape(3, 1)
    Rt = np.eye(4)
    Rt[:3, :3] = R
    Rt[:3, 3] = t[:, 0]
    return np.linalg.inv(Rt)

def render_scene(mesh, K, width, height, pose):
    scene = pyrender.Scene(bg_color=[0, 0, 0, 0])
    scene.add(mesh)

    camera = pyrender.IntrinsicsCamera(
        fx=K[0, 0], fy=K[1, 1],
        cx=K[0, 2], cy=K[1, 2],
        znear=0.1, zfar=100.0
    )

    # Flip from COLMAP to OpenGL
    flip_transform = np.eye(4)
    flip_transform[1, 1] = -1
    flip_transform[2, 2] = -1
    pose = pose @ flip_transform

    position = pose[:3, 3]
    forward = -pose[:3, 2]  # hướng nhìn (vì Z trong OpenGL là backward)
    up = pose[:3, 1]
    print("📍 Camera position:", position)
    print("👁️  Forward direction:", forward)
    print("🧭 Up direction:", up)


    print("📸 Camera pose:\n", pose)

    scene.add(camera, pose=pose)

    renderer = pyrender.OffscreenRenderer(viewport_width=width, viewport_height=height)
    color, _ = renderer.render(scene)
    renderer.delete()
    return color

def main():
    # Paths
    sparse_dir = "/Volumes/Projects/3drn/data/xe_F1_khan_60_test2/test"
    ply_file = "/Volumes/Projects/3drn/data/new_project_xeF1_100/dense/0/xe_F1_100_chualoc.obj"
    output_image = "render_test.png"

    # Load COLMAP camera & image
    cameras = read_cameras_binary(os.path.join(sparse_dir, "cameras.bin"))
    images = read_images_binary(os.path.join(sparse_dir, "images.bin"))

    # Choose 1 camera
    image = list(images.values())[0]
    camera = cameras[image.camera_id]

    K, width, height = load_intrinsics(camera)
    pose = load_extrinsics(image)

    # Load mesh
    mesh = trimesh.load(ply_file)
    if isinstance(mesh, trimesh.Scene):
        mesh = mesh.dump(concatenate=True)

    # Chuyển sang Open3D mesh
    mesh_o3d = o3d.geometry.TriangleMesh()
    mesh_o3d.vertices = o3d.utility.Vector3dVector(mesh.vertices)
    mesh_o3d.triangles = o3d.utility.Vector3iVector(mesh.faces)
    mesh_o3d.compute_vertex_normals()

    # In bounding box
    bbox = mesh_o3d.get_axis_aligned_bounding_box()
    print("📦 Mesh bounding box:")
    print("   Min:", bbox.get_min_bound())
    print("   Max:", bbox.get_max_bound())
    print("   Center:", bbox.get_center())

    mesh = pyrender.Mesh.from_trimesh(mesh)



    # Render one image
    color = render_scene(mesh, K, width, height, pose)
    cv2.imwrite(output_image, cv2.cvtColor(color, cv2.COLOR_RGB2BGR))
    print("✅ Render saved to", output_image)

if __name__ == "__main__":
    main()


📦 Mesh bounding box:
   Min: [-1.6425467  0.8469951  1.4751472]
   Max: [1.876085  3.3991566 3.9150784]
   Center: [0.11676915 2.12307585 2.6951128 ]
📍 Camera position: [-0.24831919  2.1123566  -1.97424914]
👁️  Forward direction: [0.03051526 0.00633834 0.9995142 ]
🧭 Up direction: [ 0.05172704 -0.99864995  0.00475363]
📸 Camera pose:
 [[ 0.99819494  0.05172704 -0.03051526 -0.24831919]
 [ 0.05155685 -0.99864995 -0.00633834  2.1123566 ]
 [-0.03080192  0.00475363 -0.9995142  -1.97424914]
 [ 0.          0.          0.          1.        ]]
✅ Render saved to render_test.png


In [54]:
import os
import cv2
import numpy as np
import pyrender
import trimesh
import open3d as o3d  # ✅ thêm Open3D
from colmap.scripts.python.read_write_model import read_images_binary, read_cameras_binary
from numpy.linalg import norm


def load_intrinsics(camera):
    fx, fy, cx, cy = camera.params[:4]
    K = np.array([[fx, 0, cx],
                  [0, fy, cy],
                  [0,  0,  1]])
    return K, int(camera.width), int(camera.height)

def load_extrinsics(image):
    R = image.qvec2rotmat()
    t = image.tvec.reshape(3, 1)
    Rt = np.eye(4)
    Rt[:3, :3] = R
    Rt[:3, 3] = t[:, 0]
    return np.linalg.inv(Rt)

def render_scene(mesh, K, width, height, pose):
    scene = pyrender.Scene(bg_color=[0, 0, 0, 0])
    scene.add(mesh)

    # Add directional light
    light = pyrender.DirectionalLight(color=np.ones(3), intensity=3.0)
    scene.add(light, pose=pose)  # ánh sáng theo hướng nhìn camera


    camera = pyrender.IntrinsicsCamera(
        fx=K[0, 0], fy=K[1, 1],
        cx=K[0, 2], cy=K[1, 2],
        znear=0.01, zfar=500.0  # ✅ tăng frustrum cho an toàn
    )

    # Flip từ COLMAP sang OpenGL
    flip_transform = np.eye(4)
    flip_transform[1, 1] = -1
    flip_transform[2, 2] = -1
    pose = pose @ flip_transform

    # Thông tin camera
    position = pose[:3, 3]
    forward = -pose[:3, 2]
    up = pose[:3, 1]
    print("📍 Camera position:", position)
    print("👁️  Forward direction:", forward)
    print("🧭 Up direction:", up)
    print("📸 Camera pose:\n", pose)

    scene.add(camera, pose=pose)



    renderer = pyrender.OffscreenRenderer(viewport_width=width, viewport_height=height)
    color, _ = renderer.render(scene)
    renderer.delete()
    return color

def main():
    # Paths
    sparse_dir = "/Volumes/Projects/3drn/data/xe_F1_khan_60_test2/test"
    ply_file = "/Volumes/Projects/3drn/data/new_project_xeF1_100/dense/0/xe_F1_100_chualoc.obj"
    output_image = "render_test.png"

    # Load COLMAP camera & image
    cameras = read_cameras_binary(os.path.join(sparse_dir, "cameras.bin"))
    images = read_images_binary(os.path.join(sparse_dir, "images.bin"))

    image = list(images.values())[0]
    camera = cameras[image.camera_id]

    K, width, height = load_intrinsics(camera)
    pose = load_extrinsics(image)

    # Load mesh bằng Trimesh
    mesh_trimesh = trimesh.load(ply_file)
    if isinstance(mesh_trimesh, trimesh.Scene):
        mesh_trimesh = mesh_trimesh.dump(concatenate=True)

    # Chuyển sang Open3D để tính bounding box
    mesh_o3d = o3d.geometry.TriangleMesh()
    mesh_o3d.vertices = o3d.utility.Vector3dVector(mesh_trimesh.vertices)
    mesh_o3d.triangles = o3d.utility.Vector3iVector(mesh_trimesh.faces)
    mesh_o3d.compute_vertex_normals()

    bbox = mesh_o3d.get_axis_aligned_bounding_box()
    print("📦 Mesh bounding box:")
    print("   Min:", bbox.get_min_bound())
    print("   Max:", bbox.get_max_bound())
    print("   Center:", bbox.get_center())

    # Tính khoảng cách từ camera đến model
    camera_pos = pose[:3, 3]
    model_center = bbox.get_center()
    dist = norm(model_center - camera_pos)
    print(f"📏 Distance camera → model center: {dist:.2f} units")

    # ✅ (Tuỳ chọn) scale mô hình nếu cần
    # mesh_o3d.scale(1.5, center=model_center)

    # Trả lại về dạng Trimesh để dùng với Pyrender
    mesh_for_render = trimesh.Trimesh(vertices=np.asarray(mesh_o3d.vertices),
                                      faces=np.asarray(mesh_o3d.triangles))
    mesh = pyrender.Mesh.from_trimesh(mesh_for_render)

    # Render
    color = render_scene(mesh, K, width, height, pose)
    cv2.imwrite(output_image, cv2.cvtColor(color, cv2.COLOR_RGB2BGR))
    print("✅ Render saved to", output_image)

if __name__ == "__main__":
    main()


📦 Mesh bounding box:
   Min: [-1.6425467  0.8469951  1.4751472]
   Max: [1.876085  3.3991566 3.9150784]
   Center: [0.11676915 2.12307585 2.6951128 ]
📏 Distance camera → model center: 4.68 units
📍 Camera position: [-0.24831919  2.1123566  -1.97424914]
👁️  Forward direction: [0.03051526 0.00633834 0.9995142 ]
🧭 Up direction: [ 0.05172704 -0.99864995  0.00475363]
📸 Camera pose:
 [[ 0.99819494  0.05172704 -0.03051526 -0.24831919]
 [ 0.05155685 -0.99864995 -0.00633834  2.1123566 ]
 [-0.03080192  0.00475363 -0.9995142  -1.97424914]
 [ 0.          0.          0.          1.        ]]
✅ Render saved to render_test.png


In [68]:
import os
import cv2
import numpy as np
import pyrender
import trimesh
import open3d as o3d
from colmap.scripts.python.read_write_model import read_images_binary, read_cameras_binary
from numpy.linalg import norm

def load_intrinsics(camera):
    model = camera.model

    if model in ['SIMPLE_PINHOLE', 'SIMPLE_RADIAL']:
        f, cx, cy = camera.params[:3]
        fx = fy = f
    elif model == 'PINHOLE':
        fx, fy, cx, cy = camera.params[:4]
    else:
        raise ValueError(f"⚠️ Unsupported camera model: {model}")

    K = np.array([[fx, 0, cx],
                  [0, fy, cy],
                  [0,  0,  1]])
    width, height = int(camera.width), int(camera.height)

    print(f"fx: {fx}  - fy: {fy}  - cx: {cx}  - cy: {cy}")
    if abs(cx - width / 2) > width * 0.1 or abs(cy - height / 2) > height * 0.1:
        print("⚠️  Warning: cx, cy lệch xa trung tâm ảnh. Kiểm tra lại nội tại COLMAP hoặc ảnh đã resize.")

    print("🎯 Intrinsic matrix K:\n", K)
    return K, width, height

def load_extrinsics(image):
    R = image.qvec2rotmat()
    t = image.tvec.reshape(3, 1)
    Rt = np.eye(4)
    Rt[:3, :3] = R
    Rt[:3, 3] = t[:, 0]
    return np.linalg.inv(Rt)

def render_scene(mesh, K, width, height, pose):
    # scene = pyrender.Scene(bg_color=[0, 0, 0, 0])
    scene = pyrender.Scene(bg_color=[0, 0, 0, 0], ambient_light=[0.4, 0.4, 0.4])
    scene.add(mesh)

    # Add directional light
    light = pyrender.DirectionalLight(color=np.ones(3), intensity=3.0)
    scene.add(light, pose=pose)

    # Add camera
    camera = pyrender.IntrinsicsCamera(
        fx=K[0, 0], fy=K[1, 1],
        cx=K[0, 2], cy=K[1, 2],
        znear=0.01, zfar=500.0
    )

    # Convert pose: COLMAP → OpenGL
    flip_transform = np.eye(4)
    flip_transform[1, 1] = -1
    flip_transform[2, 2] = -1
    pose = pose @ flip_transform

    # Debug camera pose
    position = pose[:3, 3]
    forward = -pose[:3, 2]
    up = pose[:3, 1]
    print("📍 Camera position:", position)
    print("👁️  Forward direction:", forward)
    print("🧭 Up direction:", up)
    print("📸 Camera pose:\n", pose)

    scene.add(camera, pose=pose)

    # Optional: Add coordinate axis for debugging
    # axis = pyrender.Mesh.from_trimesh(trimesh.creation.axis(origin_size=0.1))
    # scene.add(axis)

    renderer = pyrender.OffscreenRenderer(viewport_width=width, viewport_height=height)
    color, _ = renderer.render(scene)
    renderer.delete()
    return color

def main():
    # Paths
    sparse_dir = "/Volumes/Projects/3drn/data/xe_F1_khan_60_test2/test"
    ply_file = "/Volumes/Projects/3drn/data/new_project_xeF1_100/dense/0/xe_F1_100_chualoc.obj"
    output_image = "render_test.png"

    # Load COLMAP data
    cameras = read_cameras_binary(os.path.join(sparse_dir, "cameras.bin"))
    images = read_images_binary(os.path.join(sparse_dir, "images.bin"))
    image = list(images.values())[0]
    camera = cameras[image.camera_id]

    # Intrinsics & extrinsics
    K, width, height = load_intrinsics(camera)
    pose = load_extrinsics(image)

    # Load mesh
    mesh_trimesh = trimesh.load(ply_file)
    if isinstance(mesh_trimesh, trimesh.Scene):
        mesh_trimesh = mesh_trimesh.dump(concatenate=True)

    # Convert to Open3D for bounding box
    mesh_o3d = o3d.geometry.TriangleMesh()
    mesh_o3d.vertices = o3d.utility.Vector3dVector(mesh_trimesh.vertices)
    mesh_o3d.triangles = o3d.utility.Vector3iVector(mesh_trimesh.faces)
    mesh_o3d.compute_vertex_normals()

    bbox = mesh_o3d.get_axis_aligned_bounding_box()
    print("📦 Mesh bounding box:")
    print("   Min:", bbox.get_min_bound())
    print("   Max:", bbox.get_max_bound())
    print("   Center:", bbox.get_center())

    # Distance camera → mesh center
    camera_pos = pose[:3, 3]
    model_center = bbox.get_center()
    dist = norm(model_center - camera_pos)
    print(f"📏 Distance camera → model center: {dist:.2f} units")

    # (Optional) scale if model too small
    # mesh_o3d.scale(1.5, center=model_center)

    # Convert back to Trimesh
    mesh_for_render = trimesh.Trimesh(vertices=np.asarray(mesh_o3d.vertices),
                                      faces=np.asarray(mesh_o3d.triangles))
    mesh = pyrender.Mesh.from_trimesh(mesh_for_render)



    # Render
    color = render_scene(mesh, K, width, height, pose)
    cv2.imwrite(output_image, cv2.cvtColor(color, cv2.COLOR_RGB2BGR))
    print("✅ Render saved to", output_image)

if __name__ == "__main__":
    main()


fx: 1146.4364194057184  - fy: 1146.4364194057184  - cx: 640.0  - cy: 360.0
🎯 Intrinsic matrix K:
 [[1.14643642e+03 0.00000000e+00 6.40000000e+02]
 [0.00000000e+00 1.14643642e+03 3.60000000e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
📦 Mesh bounding box:
   Min: [-1.6425467  0.8469951  1.4751472]
   Max: [1.876085  3.3991566 3.9150784]
   Center: [0.11676915 2.12307585 2.6951128 ]
📏 Distance camera → model center: 4.68 units
📍 Camera position: [-0.24831919  2.1123566  -1.97424914]
👁️  Forward direction: [0.03051526 0.00633834 0.9995142 ]
🧭 Up direction: [ 0.05172704 -0.99864995  0.00475363]
📸 Camera pose:
 [[ 0.99819494  0.05172704 -0.03051526 -0.24831919]
 [ 0.05155685 -0.99864995 -0.00633834  2.1123566 ]
 [-0.03080192  0.00475363 -0.9995142  -1.97424914]
 [ 0.          0.          0.          1.        ]]
✅ Render saved to render_test.png


In [67]:
import os
import cv2
import numpy as np
import pyrender
import trimesh
import open3d as o3d
from colmap.scripts.python.read_write_model import read_images_binary, read_cameras_binary
from numpy.linalg import norm

def load_intrinsics(camera):
    model = camera.model

    if model in ['SIMPLE_PINHOLE', 'SIMPLE_RADIAL']:
        f, cx, cy = camera.params[:3]
        fx = fy = f
        if cy < 1e-2:
            print("⚠️ Detected invalid cy (≈ 0), overriding to image center.")
            cy = camera.height / 2
    elif model == 'PINHOLE':
        fx, fy, cx, cy = camera.params[:4]
    else:
        raise ValueError(f"⚠️ Unsupported camera model: {model}")

    K = np.array([[fx, 0, cx],
                  [0, fy, cy],
                  [0,  0,  1]])
    width, height = int(camera.width), int(camera.height)

    print(f"fx: {fx}  - fy: {fy}  - cx: {cx}  - cy: {cy}")
    if abs(cx - width / 2) > width * 0.1 or abs(cy - height / 2) > height * 0.1:
        print("⚠️  Warning: cx, cy lệch xa trung tâm ảnh. Kiểm tra lại nội tại COLMAP hoặc ảnh đã resize.")

    print("🎯 Intrinsic matrix K:\n", K)
    return K, width, height

def load_extrinsics(image):
    R = image.qvec2rotmat()
    t = image.tvec.reshape(3, 1)
    Rt = np.eye(4)
    Rt[:3, :3] = R
    Rt[:3, 3] = t[:, 0]
    return np.linalg.inv(Rt)

def render_scene(mesh, K, width, height, pose):
    # Scene with ambient light
    scene = pyrender.Scene(bg_color=[0, 0, 0, 0], ambient_light=[0.4, 0.4, 0.4])
    scene.add(mesh)

    # Add fixed-directional light (from above)
    light = pyrender.DirectionalLight(color=np.ones(3), intensity=3.0)
    light_pose = np.eye(4)
    light_pose[:3, 3] = [0, 5, 0]
    scene.add(light, pose=light_pose)

    # Add camera
    camera = pyrender.IntrinsicsCamera(
        fx=K[0, 0], fy=K[1, 1],
        cx=K[0, 2], cy=K[1, 2],
        znear=0.01, zfar=500.0
    )

    # Convert pose: COLMAP → OpenGL
    flip_transform = np.eye(4)
    flip_transform[1, 1] = -1
    flip_transform[2, 2] = -1
    pose_gl = pose @ flip_transform

    # Debug camera pose
    position = pose_gl[:3, 3]
    forward = -pose_gl[:3, 2]
    up = pose_gl[:3, 1]
    print("📍 Camera position:", position)
    print("👁️  Forward direction:", forward)
    print("🧭 Up direction:", up)
    print("📸 Camera pose:\n", pose_gl)

    scene.add(camera, pose=pose_gl)

    # Optional debug axis
    # axis = pyrender.Mesh.from_trimesh(trimesh.creation.axis(origin_size=0.1))
    # scene.add(axis)

    renderer = pyrender.OffscreenRenderer(viewport_width=width, viewport_height=height)
    color, _ = renderer.render(scene)
    renderer.delete()
    return color

def main():
    # Paths
    sparse_dir = "/Volumes/Projects/3drn/data/xe_F1_khan_60_test2/test"
    ply_file = "/Volumes/Projects/3drn/data/new_project_xeF1_100/dense/0/xe_F1_100_chualoc.obj"
    output_image = "render_test.png"

    # Load COLMAP data
    cameras = read_cameras_binary(os.path.join(sparse_dir, "cameras.bin"))
    images = read_images_binary(os.path.join(sparse_dir, "images.bin"))
    image = list(images.values())[0]
    camera = cameras[image.camera_id]

    # Intrinsics & extrinsics
    K, width, height = load_intrinsics(camera)
    pose = load_extrinsics(image)

    # Load mesh
    mesh_trimesh = trimesh.load(ply_file)
    if isinstance(mesh_trimesh, trimesh.Scene):
        mesh_trimesh = mesh_trimesh.dump(concatenate=True)

    # Convert to Open3D for bounding box
    mesh_o3d = o3d.geometry.TriangleMesh()
    mesh_o3d.vertices = o3d.utility.Vector3dVector(mesh_trimesh.vertices)
    mesh_o3d.triangles = o3d.utility.Vector3iVector(mesh_trimesh.faces)
    mesh_o3d.compute_vertex_normals()

    bbox = mesh_o3d.get_axis_aligned_bounding_box()
    print("📦 Mesh bounding box:")
    print("   Min:", bbox.get_min_bound())
    print("   Max:", bbox.get_max_bound())
    print("   Center:", bbox.get_center())

    # Distance camera → mesh center
    camera_pos = pose[:3, 3]
    model_center = bbox.get_center()
    dist = norm(model_center - camera_pos)
    print(f"📏 Distance camera → model center: {dist:.2f} units")

    # Optional scaling
    # mesh_o3d.scale(1.5, center=model_center)

    # Convert back to Trimesh for rendering
    mesh_for_render = trimesh.Trimesh(vertices=np.asarray(mesh_o3d.vertices),
                                      faces=np.asarray(mesh_o3d.triangles))

    ## Create Pyrender mesh with double_sided to avoid culling issues
    # mesh = pyrender.Mesh.from_trimesh(mesh_for_render, smooth=False, double_sided=True)
    
    # Tạo bản double-sided thủ công
    mesh_for_render_ds = make_mesh_double_sided(mesh_for_render)
    mesh = pyrender.Mesh.from_trimesh(mesh_for_render_ds, smooth=False)

    # Render
    color = render_scene(mesh, K, width, height, pose)
    cv2.imwrite(output_image, cv2.cvtColor(color, cv2.COLOR_RGB2BGR))
    print("✅ Render saved to", output_image)

def make_mesh_double_sided(tri_mesh: trimesh.Trimesh) -> trimesh.Trimesh:
    """
    Tạo mesh với cả mặt trước và sau để tránh culling trong Pyrender.
    """
    faces_back = tri_mesh.faces[:, ::-1]
    faces = np.vstack([tri_mesh.faces, faces_back])
    return trimesh.Trimesh(vertices=tri_mesh.vertices.copy(), faces=faces, process=False)

if __name__ == "__main__":
    main()


fx: 1146.4364194057184  - fy: 1146.4364194057184  - cx: 640.0  - cy: 360.0
🎯 Intrinsic matrix K:
 [[1.14643642e+03 0.00000000e+00 6.40000000e+02]
 [0.00000000e+00 1.14643642e+03 3.60000000e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
📦 Mesh bounding box:
   Min: [-1.6425467  0.8469951  1.4751472]
   Max: [1.876085  3.3991566 3.9150784]
   Center: [0.11676915 2.12307585 2.6951128 ]
📏 Distance camera → model center: 4.68 units
📍 Camera position: [-0.24831919  2.1123566  -1.97424914]
👁️  Forward direction: [0.03051526 0.00633834 0.9995142 ]
🧭 Up direction: [ 0.05172704 -0.99864995  0.00475363]
📸 Camera pose:
 [[ 0.99819494  0.05172704 -0.03051526 -0.24831919]
 [ 0.05155685 -0.99864995 -0.00633834  2.1123566 ]
 [-0.03080192  0.00475363 -0.9995142  -1.97424914]
 [ 0.          0.          0.          1.        ]]
✅ Render saved to render_test.png


In [74]:
import os
import cv2
import numpy as np
import pyrender
import trimesh
import open3d as o3d
from colmap.scripts.python.read_write_model import read_images_binary, read_cameras_binary
from numpy.linalg import norm

def load_intrinsics(camera):
    model = camera.model

    if model in ['SIMPLE_PINHOLE', 'SIMPLE_RADIAL']:
        f, cx, cy = camera.params[:3]
        fx = fy = f
        if cy < 1e-2:
            print("⚠️ Detected invalid cy (≈ 0), overriding to image center.")
            cy = camera.height / 2
    elif model == 'PINHOLE':
        fx, fy, cx, cy = camera.params[:4]
    else:
        raise ValueError(f"⚠️ Unsupported camera model: {model}")

    K = np.array([[fx, 0, cx],
                  [0, fy, cy],
                  [0,  0,  1]])
    width, height = int(camera.width), int(camera.height)

    print(f"fx: {fx}  - fy: {fy}  - cx: {cx}  - cy: {cy}")
    if abs(cx - width / 2) > width * 0.1 or abs(cy - height / 2) > height * 0.1:
        print("⚠️  Warning: cx, cy lệch xa trung tâm ảnh. Kiểm tra lại nội tại COLMAP hoặc ảnh đã resize.")

    print("🎯 Intrinsic matrix K:\n", K)
    return K, width, height

def load_extrinsics(image):
    R = image.qvec2rotmat()
    t = image.tvec.reshape(3, 1)
    Rt = np.eye(4)
    Rt[:3, :3] = R
    Rt[:3, 3] = t[:, 0]
    return np.linalg.inv(Rt)

def make_mesh_double_sided(tri_mesh: trimesh.Trimesh) -> trimesh.Trimesh:
    faces_back = tri_mesh.faces[:, ::-1]
    faces = np.vstack([tri_mesh.faces, faces_back])
    return trimesh.Trimesh(vertices=tri_mesh.vertices.copy(), faces=faces, process=False)

def render_scene(mesh, K, width, height, pose):
    # scene = pyrender.Scene(bg_color=[0, 0, 0, 0], ambient_light=[0.4, 0.4, 0.4])
    # scene = pyrender.Scene(bg_color=[0, 0, 0, 0])
    scene = pyrender.Scene(bg_color=[0, 0, 0, 0], ambient_light=[0.3, 0.3, 0.3])    
    scene.add(mesh)

    # light = pyrender.DirectionalLight(color=np.ones(3), intensity=3.0)
    # light_pose = np.eye(4)
    # light_pose[:3, 3] = [0, 5, 0]
    # scene.add(light, pose=light_pose)

    camera = pyrender.IntrinsicsCamera(
        fx=K[0, 0], fy=K[1, 1],
        cx=K[0, 2], cy=K[1, 2],
        znear=0.01, zfar=100.0
    )

    # Flip COLMAP to OpenGL convention
    flip_transform = np.eye(4)
    flip_transform[1, 1] = -1
    flip_transform[2, 2] = -1
    pose_gl = pose @ flip_transform

    position = pose_gl[:3, 3]
    forward = -pose_gl[:3, 2]
    up = pose_gl[:3, 1]
    print("📍 Camera position:", position)
    print("👁️  Forward direction:", forward)
    print("🧭 Up direction:", up)
    print("📸 Camera pose:\n", pose_gl)

    scene.add(camera, pose=pose_gl)

    # Optional: show axis
    # axis = pyrender.Mesh.from_trimesh(trimesh.creation.axis(origin_size=0.1))
    # scene.add(axis)

    renderer = pyrender.OffscreenRenderer(viewport_width=width, viewport_height=height)
    color, _ = renderer.render(scene)
    renderer.delete()
    return color

def main():
    # Paths
    sparse_dir = "/Volumes/Projects/3drn/data/xe_F1_khan_60_test2/test"
    ply_file = "/Volumes/Projects/3drn/data/new_project_xeF1_100/dense/0/xe_F1_100_chualoc.obj"
    output_image = "render_test.png"

    # Load COLMAP data
    cameras = read_cameras_binary(os.path.join(sparse_dir, "cameras.bin"))
    images = read_images_binary(os.path.join(sparse_dir, "images.bin"))
    image = list(images.values())[0]
    camera = cameras[image.camera_id]

    # Camera intrinsics & extrinsics
    K, width, height = load_intrinsics(camera)
    pose = load_extrinsics(image)

    # Load mesh (.obj with .mtl and texture)
    mesh_trimesh = trimesh.load(ply_file, force='mesh', process=True, maintain_order=True)
    if isinstance(mesh_trimesh, trimesh.Scene):
        mesh_trimesh = mesh_trimesh.dump(concatenate=True)

    # Compute bounding box (optional)
    mesh_o3d = o3d.geometry.TriangleMesh()
    mesh_o3d.vertices = o3d.utility.Vector3dVector(mesh_trimesh.vertices)
    mesh_o3d.triangles = o3d.utility.Vector3iVector(mesh_trimesh.faces)
    mesh_o3d.compute_vertex_normals()

    bbox = mesh_o3d.get_axis_aligned_bounding_box()
    print("📦 Mesh bounding box:")
    print("   Min:", bbox.get_min_bound())
    print("   Max:", bbox.get_max_bound())
    print("   Center:", bbox.get_center())

    camera_pos = pose[:3, 3]
    dist = norm(bbox.get_center() - camera_pos)
    print(f"📏 Distance camera → model center: {dist:.2f} units")

    # Check if texture available
    has_texture = (
        hasattr(mesh_trimesh.visual, 'material') and 
        getattr(mesh_trimesh.visual.material, 'image', None) is not None
    )
    print(f"🎨 Has texture: {has_texture}")

    # Create Pyrender mesh
    if has_texture:
        mesh = pyrender.Mesh.from_trimesh(mesh_trimesh, smooth=False)
    else:
        print("⚠️ No texture found. Using double-sided mesh as fallback.")
        mesh_ds = make_mesh_double_sided(mesh_trimesh)
        mesh = pyrender.Mesh.from_trimesh(mesh_ds, smooth=False)

    # Render
    color = render_scene(mesh, K, width, height, pose)
    cv2.imwrite(output_image, cv2.cvtColor(color, cv2.COLOR_RGB2BGR))
    print("✅ Render saved to", output_image)

if __name__ == "__main__":
    main()


fx: 1146.4364194057184  - fy: 1146.4364194057184  - cx: 640.0  - cy: 360.0
🎯 Intrinsic matrix K:
 [[1.14643642e+03 0.00000000e+00 6.40000000e+02]
 [0.00000000e+00 1.14643642e+03 3.60000000e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
📦 Mesh bounding box:
   Min: [-1.6425467  0.8469951  1.4751472]
   Max: [1.876085  3.3991566 3.9150784]
   Center: [0.11676915 2.12307585 2.6951128 ]
📏 Distance camera → model center: 4.68 units
🎨 Has texture: False
⚠️ No texture found. Using double-sided mesh as fallback.
📍 Camera position: [-0.24831919  2.1123566  -1.97424914]
👁️  Forward direction: [0.03051526 0.00633834 0.9995142 ]
🧭 Up direction: [ 0.05172704 -0.99864995  0.00475363]
📸 Camera pose:
 [[ 0.99819494  0.05172704 -0.03051526 -0.24831919]
 [ 0.05155685 -0.99864995 -0.00633834  2.1123566 ]
 [-0.03080192  0.00475363 -0.9995142  -1.97424914]
 [ 0.          0.          0.          1.        ]]
✅ Render saved to render_test.png
